### ISSUE TITLE
Closed tickets should be reopened when receiving a new reply

### ISSUE THREAD

**Issue by iandunn** [SupportFlow/supportflow#235]
If an agent closes a ticket, and then a customer replies, the ticket should be reopened.

**Comment by DavidAnderson684** [comment]
If/when this is implemented, it'd be good to allow that instead, if the ticket has been closed for more than a defined period, then the customer instead gets a response that says "please open new ticket".

Use case: customers who re-cycle old tickets to lodge new, unrelated support requests, months later (I've seen it happen lots of times...).

**Comment by iandunn** [comment]
That's a good point.

I think it'd be better to automatically create a new ticket, rather than asking the user to do it, though. We'd have to alert the agent that that happened, and ask them to update the title to make it relevant to the actual content of the new request.

But what would be a good cut-off period? If it's 2 months later, then most of the time it'll be a separate issue, but it could still be the same one; and a user could just as easily respond a hour later with a completely separate issue. So instead, maybe it'd be better to have a button that the agent can click to split a reply off into a new ticket?

Regardless, I think that's outside the scope of this issue. We should make sure tickets are reopened on new replies because that's an immediate bug. Once that's done, we can look at enhancing the functionality to solve the problem of users re-using tickets inappropriately.

**Comment by kovshenin** [comment]
No cut-off period for the reasons @iandunn mentioned, somebody could be inquiring about a year-old issue which suddenly broke again, and reopening the old ticket with all the history makes the most sense.

If the issues are not relevant, I don't think that the customers should be bothered to open a new ticket. Maybe agents should be able to create new topics from existing replies, as well as merge two topics together in case a customer is just following up on a previous e-mail he sent that nobody replied to.
