### ISSUE TITLE
Review List Table method visibility

### ISSUE THREAD

**Issue by obenland** [SupportFlow/supportflow#238]
https://core.trac.wordpress.org/changeset/31210 broke SupportFlow on dotorg, because [column_default is marked as protected](https://github.com/SupportFlow/supportflow/blob/master/classes/class-supportflow-table.php#L32).

The change was adjusted in https://core.trac.wordpress.org/changeset/31211, but it might be worth reconsidering the visibility of `column_default()` for SupportFlow.

**Comment by iandunn** [comment]
Fixed now, thanks for reporting this to Scott and here :)
