### ISSUE TITLE
 Fatal error: Call to undefined function imap_timeout()

### ISSUE THREAD

**Issue by dnutbourne** [SupportFlow/supportflow#239]
When adding new email account through the form on SupportFlow->E-Mail Accounts.

**Comment by VarunAgw** [comment]
You need to ask your web host to upgrade your PHP version

**Comment by dnutbourne** [comment]
Cheers. Turns out the IMAP extension was not activated.

**Comment by iandunn** [comment]
Re-opening because we shouldn't assume that the IMAP extension is enabled. The code should only call `imap_*` functions it they exist.

**Comment by iandunn** [comment]
We should also add an `admin_notice` or some other way of letting the user know that IMAP won't work at all, and that they'll need to contact their host to have it enabled. Otherwise nothing will work, but they won't know why.
