### ISSUE TITLE
New tickets created from replies when ticket status changed

### ISSUE THREAD

**Issue by dnutbourne** [SupportFlow/supportflow#241]
Hi,
I've found that when the status of a ticket has been changed from 'New', any replies to the ticket from the Customer (i.e. replying to the Agent via email) are not added to the ticket correctly. Instead, a new ticket is created.

1. Ticket "A" is created
2. Agent changes the ticket status to 'open' and replies to the customer
3. Customer replies through email
4. A new ticket: "Re: [Website] A [Code]" is created from that email.

If the status is kept, or reset to, 'New', the replies are added to the original ticket correctly.
I've tested this with both a Gmail and a branded email address for the customer side. The Support inbox is a Gmail account.

**Comment by techjewel** [comment]
I am facing the same issue! is it happened for any special email hosts or this is for all emails hosts? @iandunn

**Comment by iandunn** [comment]
I'm guessing that it's affecting all hosts.

@brandondove, do you have time to take a look at this?

**Comment by brandondove** [comment]
Yep. I'll take a look today.

**Comment by iandunn** [comment]
Awesome, thanks :)

**Comment by brandondove** [comment]
I have confirmed this on my end. Looking into getting a fix in place.
