### ISSUE TITLE
Reconsider numeric topic tags rather than random 8-character strings.

### ISSUE THREAD

**Issue by kovshenin** [SupportFlow/supportflow#251]
Currently for all outgoing e-mail SupportFlow appends a random alfanumeric 8-character string at the end, such as:

`[Website Name] This is a topic reply [eo37TbwG]`

This looks a bit weird, especially for users who have no clue what it means or does. Some might actually delete it from the subject line thinking it's a bug. There's no good reason for the string itself to be random, so let's consider moving to the old-fashioned numeric IDs.

`#12345: This is a topic reply`

And while we're at it, how about we drop the website name from the subject line, and put it in the `From` field instead, which will give more room for the subject itself. And if users want to customize that, they could with the various filters.

**Comment by iandunn** [comment]
+1

**Comment by Viper007Bond** [comment]
Sounds good to me.
