### ISSUE TITLE
Check boxes sometimes do not reinitialise states

### ISSUE THREAD

**Issue by Kenshino** [SupportFlow/supportflow#263]
One of our questions offers a checkbox that simply doesn't apply the 'checked' attribute properly to the checkbox.

I imagine it's because I'm using ampersands in my question - when saved to the database, it's encoded. But when checked against in the html tags, they don't exactly match?

Check it out at https://2016.singapore.wordcamp.org/wp-admin/post.php?post=1557&action=edit

and you can see it by editing my attendee data https://2016.singapore.wordcamp.org/wp-admin/post.php?post=2211&action=edit

**Comment by iandunn** [comment]
It sounds like this was meant for the CampTix repo; do you mind re-creating it there?

**Comment by Kenshino** [comment]
My bad. Will do so :)
